name: Checks
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: "Use NodeJS 20"
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: "Setup npm"
      run: |
        npm set @ewuharun:registry=https://npm.pkg.github.com/ewuharun
        npm set "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}"

    - name: Install dependencies
      run: |
        npm run build

    - name: Run tests # Run tests of all packages
      run: npm run test