name: Publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: "Use NodeJS 20"
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: "Setup npm"
      run: |
        npm set @ewuharun:registry=https://npm.pkg.github.com/
        npm set "//npm.pkg.github.com/:_authToken=${{ secrets.GIT_TOKEN }}"

    - name: "Version and publish" # Interesting step
      env:
        GH_TOKEN: ${{ secrets.GIT_TOKEN }}
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor}}@users.noreply.github.com"

        if [ ${{ github.base_ref }} = development ]; then
          npx lerna version --conventional-commits --conventional-prerelease --preid beta --yes
        else
          npx lerna version --conventional-commits --conventional-graduate --yes
        fi

        npx lerna publish from-git --yes
